In [1]:
#Importing packages needed
import lxml
import re
import numpy as np
import pandas as pd

from bs4 import BeautifulSoup
from requests import get

#creating the list of urls
url1=[]

pages= np.arange(1,10000,249)
for i in pages:
    url1.append("https://www.imdb.com/search/title/?title_type=feature,tv_series&count=249&start=" + str(i)+"&ref_=adv_nxt") 

#creating web scraping function
class IMDB(object):
	"""docstring for IMDB"""
	def __init__(self, url):
		super(IMDB, self).__init__()
		page = get(url)

		self.soup = BeautifulSoup(page.content, 'lxml')

	def articleTitle(self):
		return self.soup.find("h1", class_="header").text.replace("\n","")

	def bodyContent(self):
		content = self.soup.find(id="main")
		return content.find_all("div", class_="lister-item mode-advanced")

	def movieData(self):
		movieFrame = self.bodyContent()
		movieTitle = []
		movieDate = []
		movieRunTime = []
		movieGenre = []
		movieRating = []
		movieScore = []
		movieDescription = []
		movieDirector = []
		movieStars = []
		movieVotes = []
		movieGross = []
		movieMetascore1 = []
		movieMetascore2 = []
		movieMetascore3 = []
		for movie in movieFrame:
			movieFirstLine = movie.find("h3", class_="lister-item-header")
			movieTitle.append(movieFirstLine.find("a").text)
			movieDate.append(re.sub(r"[()]","", movieFirstLine.find_all("span")[-1].text))
			try:
				movieRunTime.append(movie.find("span", class_="runtime").text[:-4])
			except:
				movieRunTime.append(np.nan)
#			movieGenre.append(movie.find("span", class_="genre").text.rstrip().replace("\n","").split(","))
			try:
				movieRating.append(movie.find("strong").text)
			except:
				movieRating.append(np.nan)
			try:
				movieScore.append(movie.find("span", class_="metascore unfavorable" ).text.rstrip())
			except:
				movieScore.append(np.nan)
			movieDescription.append(movie.find_all("p", class_="text-muted")[-1].text.lstrip())
			movieCast = movie.find("p", class_="")

			try:
				casts = movieCast.text.replace("\n","").split('|')
				casts = [x.strip() for x in casts]
				casts = [casts[i].replace(j, "") for i,j in enumerate(["Director:", "Stars:"])]
				movieDirector.append(casts[0])
				movieStars.append([x.strip() for x in casts[1].split(",")])
			except:
				casts = movieCast.text.replace("\n","").strip()
				movieDirector.append(np.nan)
				movieStars.append([x.strip() for x in casts.split(",")])

			movieNumbers = movie.find_all("span", attrs={"name": "nv"})

			if len(movieNumbers) == 2:
				movieVotes.append(movieNumbers[0].text)
				movieGross.append(movieNumbers[1].text)
			elif len(movieNumbers) == 1:
				movieVotes.append(movieNumbers[0].text)
				movieGross.append(np.nan)
			else:
				movieVotes.append(np.nan)
				movieGross.append(np.nan)

			movieNumbers2 = movie.find_all("span", class_="metascore unfavorable")

			if len(movieNumbers2) == 1:
				movieMetascore1.append(movieNumbers2[0].text)
			else:
				movieMetascore1.append(np.nan)

			movieNumbers3 = movie.find_all("span", class_="metascore favorable")

			if len(movieNumbers3) == 1:
				movieMetascore2.append(movieNumbers3[0].text)
			else:
				movieMetascore2.append(np.nan)
                
                
			movieNumbers4 = movie.find_all("span", class_="metascore mixed")

			if len(movieNumbers4) == 1:
				movieMetascore3.append(movieNumbers4[0].text)
			else:
				movieMetascore3.append(np.nan)


		movieData = [movieTitle, movieDate, movieRunTime,  movieRating, movieScore, movieDescription,
							movieDirector, movieStars, movieVotes, movieGross, movieMetascore1, movieMetascore2, movieMetascore3]
		return movieData
    
#Applying IMDB function on lists of urls and storing data
data = []
for i in range(40):
    if __name__ == '__main__':
        site1=IMDB(url1[i])
        print("Subject: ", site1.articleTitle())
        data.append(site1.movieData())
#	for i in range(len(data)):
#		print(data[i][:])

Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)
Subject:  Feature Film/TV Series(Sorted by Popularity Ascending)

In [2]:
#Appending data from 40 urls
for i in range(len(data)):
    data[i]=pd.DataFrame(data[i]).transpose()
    
df=data[0].append([data[1],data[2],data[3],data[4],data[5],
data[6],data[7],data[8],data[9],data[10],data[11],data[12],data[13],data[14],data[15],data[16],data[17],data[18],data[19],data[20],
data[21],data[22],data[23],data[24],data[25],data[26],data[27],data[28],data[29],
data[30],data[31],data[32],data[33],data[34],data[35],data[36],data[37],data[38],data[39]])

In [3]:
df_new = df.rename(columns={1: 'year'})
df_new.head()

,0,year,2,3,4,5,6,7,8,9,10,11,12
0,Ozark,2017–,60,8.3,NaN,A financial adviser drags his family from Chic...,NaN,"[Stars:Jason Bateman, Laura Linney, Sofia Hubl...","132,749",NaN,NaN,NaN,NaN
1,Money Heist,2017–,70,8.5,NaN,An unusual group of robbers attempt to carry o...,NaN,"[Stars:Úrsula Corberó, Álvaro Morte, Itziar It...","207,378",NaN,NaN,NaN,NaN
2,The Platform,2019,94,7.0,NaN,A vertical prison with one cell per level. Two...,Galder Gaztelu-Urrutia,"[Ivan Massagué, Zorion Eguileor, Antonia San J...","70,594",NaN,NaN,73,NaN
3,Westworld,2016–,62,8.7,NaN,Set at the intersection of the near future and...,NaN,"[Stars:Evan Rachel Wood, Jeffrey Wright, Ed Ha...","386,178",NaN,NaN,NaN,NaN
4,The Walking Dead,2010–,44,8.2,NaN,Sheriff Deputy Rick Grimes wakes up from a com...,NaN,"[Stars:Andrew Lincoln, Norman Reedus, Melissa ...","820,948",NaN,NaN,NaN,NaN

In [4]:
#Creating a column for metascore 
df_new['meta']=np.nan

In [5]:
#Assigning value to metascore column
for i in range(len(df_new)):
    if (pd.notnull(df_new.iloc[i,10])):
        df_new.iloc[i,13]=df_new.iloc[i,10]
    elif (pd.notnull(df_new.iloc[i,11])):
        df_new.iloc[i,13]=df_new.iloc[i,11]
    else: 
        df_new.iloc[i,13]=df_new.iloc[i,12]

In [6]:
df_new.head()

,0,year,2,3,4,5,6,7,8,9,10,11,12,meta
0,Ozark,2017–,60,8.3,NaN,A financial adviser drags his family from Chic...,NaN,"[Stars:Jason Bateman, Laura Linney, Sofia Hubl...","132,749",NaN,NaN,NaN,NaN,NaN
1,Money Heist,2017–,70,8.5,NaN,An unusual group of robbers attempt to carry o...,NaN,"[Stars:Úrsula Corberó, Álvaro Morte, Itziar It...","207,378",NaN,NaN,NaN,NaN,NaN
2,The Platform,2019,94,7.0,NaN,A vertical prison with one cell per level. Two...,Galder Gaztelu-Urrutia,"[Ivan Massagué, Zorion Eguileor, Antonia San J...","70,594",NaN,NaN,73,NaN,73
3,Westworld,2016–,62,8.7,NaN,Set at the intersection of the near future and...,NaN,"[Stars:Evan Rachel Wood, Jeffrey Wright, Ed Ha...","386,178",NaN,NaN,NaN,NaN,NaN
4,The Walking Dead,2010–,44,8.2,NaN,Sheriff Deputy Rick Grimes wakes up from a com...,NaN,"[Stars:Andrew Lincoln, Norman Reedus, Melissa ...","820,948",NaN,NaN,NaN,NaN,NaN

In [7]:
#Dropping metascore columns 
movies_df=df_new.drop(columns=[4,10,11,12],axis=1)

In [8]:
#Renaming columns
movies_df.columns = ['title','year','duration','rating','description','director','actors','votes','budget','metascore']

In [9]:
movies_df.head()

,title,year,duration,rating,description,director,actors,votes,budget,metascore
0,Ozark,2017–,60,8.3,A financial adviser drags his family from Chic...,NaN,"[Stars:Jason Bateman, Laura Linney, Sofia Hubl...","132,749",NaN,NaN
1,Money Heist,2017–,70,8.5,An unusual group of robbers attempt to carry o...,NaN,"[Stars:Úrsula Corberó, Álvaro Morte, Itziar It...","207,378",NaN,NaN
2,The Platform,2019,94,7.0,A vertical prison with one cell per level. Two...,Galder Gaztelu-Urrutia,"[Ivan Massagué, Zorion Eguileor, Antonia San J...","70,594",NaN,73
3,Westworld,2016–,62,8.7,Set at the intersection of the near future and...,NaN,"[Stars:Evan Rachel Wood, Jeffrey Wright, Ed Ha...","386,178",NaN,NaN
4,The Walking Dead,2010–,44,8.2,Sheriff Deputy Rick Grimes wakes up from a com...,NaN,"[Stars:Andrew Lincoln, Norman Reedus, Melissa ...","820,948",NaN,NaN

In [10]:
#Subsetting the data to tv shows subset
TV = movies_df[movies_df['year'].str.contains('–')]
TV

,title,year,duration,rating,description,director,actors,votes,budget,metascore
0,Ozark,2017–,60,8.3,A financial adviser drags his family from Chic...,NaN,"[Stars:Jason Bateman, Laura Linney, Sofia Hubl...","132,749",NaN,NaN
1,Money Heist,2017–,70,8.5,An unusual group of robbers attempt to carry o...,NaN,"[Stars:Úrsula Corberó, Álvaro Morte, Itziar It...","207,378",NaN,NaN
3,Westworld,2016–,62,8.7,Set at the intersection of the near future and...,NaN,"[Stars:Evan Rachel Wood, Jeffrey Wright, Ed Ha...","386,178",NaN,NaN
4,The Walking Dead,2010–,44,8.2,Sheriff Deputy Rick Grimes wakes up from a com...,NaN,"[Stars:Andrew Lincoln, Norman Reedus, Melissa ...","820,948",NaN,NaN
10,Game of Thrones,2011–2019,57,9.3,Nine noble families fight for control over the...,NaN,"[Stars:Emilia Clarke, Peter Dinklage, Kit Hari...","1,655,779",NaN,NaN
11,Better Call Saul,2015–,46,8.7,The trials and tribulations of criminal lawyer...,NaN,"[Stars:Bob Odenkirk, Rhea Seehorn, Jonathan Ba...","278,580",NaN,NaN
12,Killing Eve,2018–,42,8.3,"After a series of events, the lives of a secur...",NaN,"[Stars:Sandra Oh, Jodie Comer, Fiona Shaw, Kim...","64,701",NaN,NaN
14,Star Trek: Picard,2020–,46,7.7,Follow-up series to Star Trek: The Next Genera...,NaN,"[Stars:Patrick Stewart, Alison Pill, Isa Brion...","29,019",NaN,NaN
18,Grey's Anatomy,2005–,41,7.6,A drama centered on the personal and professio...,NaN,"[Stars:Ellen Pompeo, Chandra Wilson, James Pic...","230,603",NaN,NaN
19,The Mandalorian,2019–,30,8.7,The travels of a lone bounty hunter in the out...,NaN,"[Stars:Pedro Pascal, Carl Weathers, Rio Hackfo...","150,958",NaN,NaN
21,Outlander,2014–,64,8.4,An English combat nurse from 1945 is mysteriou...,NaN,"[Stars:Caitriona Balfe, Sam Heughan, Duncan La...","107,590",NaN,NaN
23,Homeland,2011–2020,55,8.3,A bipolar CIA operative becomes convinced a pr...,NaN,"[Stars:Claire Danes, Mandy Patinkin, Damian Le...","292,919",NaN,NaN
24,Peaky Blinders,2013–,60,8.8,"A gangster family epic set in 1919 Birmingham,...",NaN,"[Stars:Cillian Murphy, Paul Anderson, Helen Mc...","273,890",NaN,NaN
25,Breaking Bad,2008–2013,49,9.5,A high school chemistry teacher diagnosed with...,NaN,"[Stars:Bryan Cranston, Aaron Paul, Anna Gunn, ...","1,328,397",NaN,NaN
26,The Office,2005–2013,22,8.9,A mockumentary on a group of typical office wo...,NaN,"[Stars:Steve Carell, Jenna Fischer, John Krasi...","346,846",NaN,NaN
27,All American,2018–,45,7.6,When a star high school football player from S...,NaN,"[Stars:Daniel Ezra, Samantha Logan, Michael Ev...","4,193",NaN,NaN
28,Brooklyn Nine-Nine,2013–,22,8.4,"Jake Peralta, an immature, but talented N.Y.P....",NaN,"[Stars:Andy Samberg, Stephanie Beatriz, Terry ...","185,506",NaN,NaN
29,Vikings,2013–,44,8.6,Vikings transports us to the brutal and myster...,NaN,"[Stars:Katheryn Winnick, Gustaf Skarsgård, Ale...","382,621",NaN,NaN
32,Freud,2020–,55,6.6,"Young psychoanalyst, Sigmund Freud, investigat...",NaN,"[Stars:Robert Finster, Ella Rumpf, Georg Fried...","4,670",NaN,NaN
33,Supernatural,2005–,44,8.4,Two brothers follow their father's footsteps a...,NaN,"[Stars:Jared Padalecki, Jensen Ackles, Jim Bea...","370,895",NaN,NaN
34,Rick and Morty,2013–,23,9.2,An animated series that follows the exploits o...,NaN,"[Stars:Justin Roiland, Chris Parnell, Spencer ...","328,934",NaN,NaN
35,The Good Doctor,2017–,41,8.2,"Shaun Murphy, a young surgeon with autism and ...",NaN,"[Stars:Freddie Highmore, Nicholas Gonzalez, An...","54,181",NaN,NaN
38,Community,2009–2015,22,8.5,A suspended lawyer is forced to enroll in a co...,NaN,"[Stars:Joel McHale, Danny Pudi, Donald Glover,...","183,653",NaN,NaN
39,Schitt's Creek,2015–2020,22,8.3,When rich video-store magnate Johnny Rose and ...,NaN,"[Stars:Eugene Levy, Catherine O'Hara, Dan Levy...","29,849",NaN,NaN
40,The Blacklist,2013–,43,8.0,"A new FBI profiler, Elizabeth Keen, has her en...",NaN,"[Stars:James Spader, Megan Boone, Diego Klatte...","177,176",NaN,NaN
41,Elite,2018–,60,7.6,When three working-class teenagers begin atten...,NaN,"[Stars:Itzan Escamilla, Miguel Bernardeau, Álv...","32,700",NaN,NaN
42,Stranger Things,2016–,51,8.8,"When a young boy disappears, his mother, a pol...",NaN,"[Stars:Millie Bobby Brown, Finn Wolfhard, Wino...","723,089",NaN,NaN
44,Hunters,2020–,60,7.2,"In 1977, in New York City, a troubled young Je...",NaN,"[Stars:Al Pacino, Logan Lerman, Lena Olin, Jer...","18,644",NaN,NaN
46,The Witcher,2019–,60,8.3,"Geralt of Rivia, a solitary monster hunter, st...",NaN,"[Stars:Henry Cavill, Freya Allan, Anya Chalotr...","240,223",NaN,NaN
47,Friends,1994–2004,22,8.9,Follows the personal and professional lives of...,NaN,"[Stars:Jennifer Aniston, Courteney Cox, Lisa K...","748,595",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
97,Turn Up Charlie,2019–,30,7.1,"Charlie, a struggling DJ and eternal bachelor ...",NaN,"[Stars:Idris Elba, Piper Perabo, Frankie Herve...","5,803",NaN,NaN
112,La caza. Monteperdido,2019–2020,70,7.2,The unsolved case of two girls who disappeared...,NaN,"[Stars:Megan Montaner, Alain Hernández, Beatri...",274,NaN,NaN
113,Avonlea,1990–1996,60,8.5,A young rich girl is sent to live with relativ...,NaN,"[Stars:Zachary Bennett, Lally Cadeau, Mag Ruff...","3,738",NaN,NaN
116,Trolls: The Beat Goes On!,2018–,25,5.8,"The party keeps on going for Poppy, Branch and...",NaN,"[Stars:Amanda Leighton, Sean T. Krishnan, Kevi...",563,NaN,NaN
123,Superman and Lois,2020–,42,NaN,Follow the world's most famous super hero and ...,NaN,"[Stars:Emmanuelle Chriqui, Jordan Elsass, Alex...",NaN,NaN,NaN
124,Noragami,2014–2016,24,7.9,A minor god seeking to gain widespread worship...,NaN,"[Stars:Hiroshi Kamiya, Maaya Uchida, Yûki Kaji...","9,289",NaN,NaN
133,The Test Case,2017–,NaN,8.6,Preparing to be the Indian Army's first female...,NaN,"[Stars:Nimrat Kaur, Akshay Oberoi, Atul Kulkar...",922,NaN,NaN
137,Undeclared,2001–2003,22,7.9,"College freshman Steve Karp, his girlfriend an...",NaN,"[Stars:Jay Baruchel, Carla Gallo, Charlie Hunn...","15,994",NaN,NaN
145,House of Payne,2006–,30,3.5,A multi-generational family lives together und...,NaN,"[Stars:LaVan Davis, Cassi Davis, Lance Gross, ...","5,658",NaN,NaN
146,Profilage,2009–,52,7.6,Chloé Saint-Laurent is a profiler and works wi...,NaN,"[Stars:Raphaël Ferret, Jean-Michel Martial, Ph...",839,NaN,NaN
147,Indian Summers,2015–2016,NaN,7.2,Drama set in 1932 during the final years of Br...,NaN,"[Stars:Henry Lloyd-Hughes, Jemima West, Julie ...","3,393",NaN,NaN
150,Archie Bunker's Place,1979–1983,60,6.4,"The further misadventures of Archie Bunker, no...",NaN,"[Stars:Carroll O'Connor, Danielle Brisebois, A...",878,NaN,NaN
164,Syucheu,2018–,60,7.2,Hotshot lawyer Choi Kang Seok is known as the ...,NaN,"[Stars:Dong-Gun Jang, Hyung-shik Park, Gwi-hwa...",348,NaN,NaN
178,Yu Yu Hakusho: Ghost Files,1992–1995,24,8.4,"One day, 14-year-old Yusuke Urameshi suddenly ...",NaN,"[Stars:Nozomu Sasaki, Justin Cook, Christopher...","10,529",NaN,NaN
182,Heathers,2018–,30,5.6,"TV version of a 1988 black comedy, 'Heathers,'...",NaN,"[Stars:Grace Victoria Cox, Melanie Field, Jame...","2,136",NaN,NaN
185,Matador,1978–1982,67,9.2,"A man comes to Korsbæk, Denmark, in 1929, open...",NaN,"[Stars:Jørgen Buckhøj, Buster Larsen, Ghita Nø...","3,807",NaN,NaN
186,American Pickers,2010–,60,7.0,Mike and Frank are pickers that travel the cou...,NaN,"[Stars:Mike Wolfe, Danielle Colby-Cushman, Fra...","6,525",NaN,NaN
191,No Activity,2017–,30,6.7,Set against the world of a major drug cartel b...,NaN,"[Stars:Patrick Brammall, Sunita Mani, Amy Seda...",847,NaN,NaN
192,The Many Loves of Dobie Gillis,1959–1963,30,7.7,Sensitive teenager Dobie Gillis exasperates hi...,NaN,"[Stars:Dwayne Hickman, Bob Denver, Frank Fayle...","1,356",NaN,NaN
193,Mystery!: Cadfael,1994–1996,75,8.1,The medieval era cases of a Crusader-turned-Mo...,NaN,"[Stars:Derek Jacobi, Michael Culver, Julian Fi...","2,094",NaN,NaN
202,The Village,2013–,60,7.7,Follows the residents of one English village a...,NaN,"[Stars:David Ryall, Maxine Peake, John Simm, C...","1,740",NaN,NaN
203,Land of the Giants,1968–1970,60,7.1,A spaceship from Earth crash-lands on an Earth...,NaN,"[Stars:Gary Conway, Don Matheson, Stefan Arngr...","2,034",NaN,NaN
207,Fatmagül'ün Suçu Ne?,2010–2012,90,5.5,Fatmagul Sucu Ne (What is Fatmagul's Fault?) i...,NaN,"[Stars:Beren Saat, Engin Akyürek, Firat Çelik,...","5,309",NaN,NaN
211,"Sex, Explained",2020–,NaN,6.9,From the biology of attraction to the history ...,NaN,"[Stars:Janelle Monáe, Lisa Diamond, Shareen Jo...","1,329",NaN,NaN
215,Moominvalley,2019–,22,7.0,A 2019 adaptation of Tove Jansson's loved body...,NaN,"[Stars:Matt Berry, Warwick Davis, Taron Egerto...",460,NaN,NaN
217,Zoom,1997–,30,7.1,"A group of older children do arts and crafts, ...",NaN,"[Stars:Caroline Botelho, Kenny Yates, Alisa Be...","1,087",NaN,NaN
227,Black and White Love,2017–2018,140,8.1,A doctor who has devoted herself to healing ot...,NaN,"[Stars:Birce Akalay, Muhammet Uzuner, Ibrahim ...","4,104",NaN,NaN
233,'Til Death,2006–2010,21,6.5,A pair of newlyweds move in next door to a vet...,NaN,"[Stars:Brad Garrett, Joely Fisher, Kat Foster,...","5,780",NaN,NaN
243,Romaenseuneun Byulchaekboorok,2019–,NaN,8.1,Cha Eun Ho is a successful and handsome writer...,NaN,"[Stars:Park Gyuyoung, Eu-Gene Jeong, Han-chul ...","1,627",NaN,NaN
244,The Honeymooners,1955–1956,30,8.6,A bus driver and his sewer worker friend strug...,NaN,"[Stars:Jackie Gleason, Art Carney, Audrey Mead...","4,424",NaN,NaN

In [11]:
#Subsetting the data to movies subset
movies = movies_df[~movies_df['year'].str.contains('–')]
movies

,title,year,duration,rating,description,director,actors,votes,budget,metascore
2,The Platform,2019,94,7.0,A vertical prison with one cell per level. Two...,Galder Gaztelu-Urrutia,"[Ivan Massagué, Zorion Eguileor, Antonia San J...","70,594",NaN,73
5,The Gentlemen,2019,113,8.0,An American expat tries to sell off his highly...,Guy Ritchie,"[Matthew McConaughey, Charlie Hunnam, Michelle...","87,279",NaN,51
6,Once Upon a Time... in Hollywood,2019,161,7.7,A faded television actor and his stunt double ...,Quentin Tarantino,"[Leonardo DiCaprio, Brad Pitt, Margot Robbie, ...","429,151",$142.50M,83
7,Contagion,2011,106,6.7,"Healthcare professionals, government officials...",Steven Soderbergh,"[Matt Damon, Kate Winslet, Jude Law, Gwyneth P...","248,071",$75.66M,70
8,Onward,I 2020,102,7.5,Two elven brothers embark on a quest to bring ...,Dan Scanlon,"[Tom Holland, Chris Pratt, Julia Louis-Dreyfus...","35,234",NaN,61
9,Bad Boys For Life,2020,124,6.9,Miami detectives Mike Lowrey and Marcus Burnet...,"Directors:Adil El Arbi, Bilall Fallah","[Will Smith, Martin Lawrence, Vanessa Hudgens,...","64,123",NaN,59
13,The Invisible Man,2020,124,7.2,When Cecilia's abusive ex takes his own life a...,Leigh Whannell,"[Elisabeth Moss, Oliver Jackson-Cohen, Harriet...","70,658",NaN,72
15,Underwater,2020,95,5.9,A crew of oceanic researchers working for a de...,William Eubank,"[Kristen Stewart, Vincent Cassel, T.J. Miller,...","22,870",NaN,48
16,Knives Out,2019,131,8.0,A detective investigates the death of a patria...,Rian Johnson,"[Daniel Craig, Chris Evans, Ana de Armas, Jami...","259,480",$165.36M,82
17,Bloodshot,2020,109,5.7,"Ray Garrison, a slain soldier, is re-animated ...",Dave Wilson,"[Vin Diesel, Eiza González, Sam Heughan, Toby ...","23,598",NaN,44
20,1917,2019,119,8.4,"April 6th, 1917. As a regiment assembles to wa...",Sam Mendes,"[Dean-Charles Chapman, George MacKay, Daniel M...","266,023",$159.23M,78
22,Parasite,2019,132,8.6,"A poor family, the Kims, con their way into be...",Bong Joon Ho,"[Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo...","351,037",$53.37M,96
30,The Hunt,II 2020,90,6.4,Twelve strangers wake up in a clearing. They d...,Craig Zobel,"[Betty Gilpin, Hilary Swank, Ike Barinholtz, W...","21,848",NaN,50
31,Birds of Prey: And the Fantabulous Emancipatio...,2020,109,6.2,"After splitting with the Joker, Harley Quinn j...",Cathy Yan,"[Margot Robbie, Rosie Perez, Mary Elizabeth Wi...","87,602",NaN,60
36,Star Wars: Episode IX - The Rise of Skywalker,2019,142,6.7,The surviving members of the resistance face t...,J.J. Abrams,"[Carrie Fisher, Mark Hamill, Adam Driver, Dais...","292,725",$515.20M,53
37,Vivarium,2019,97,5.8,A young couple looking for the perfect home fi...,Lorcan Finnegan,"[Imogen Poots, Danielle Ryan, Molly McCann, Je...","9,619",NaN,64
43,Jumanji: The Next Level,2019,123,6.7,"In Jumanji: The Next Level, the gang is back b...",Jake Kasdan,"[Dwayne Johnson, Jack Black, Kevin Hart, Karen...","124,582",$316.83M,58
45,The Call of the Wild,2020,100,6.8,A sled dog struggles for survival in the wilds...,Chris Sanders,"[Harrison Ford, Omar Sy, Cara Gee, Dan Stevens]","13,535",NaN,47
51,Spenser Confidential,2020,111,6.2,"When two Boston police officers are murdered, ...",Peter Berg,"[Mark Wahlberg, Winston Duke, Alan Arkin, Iliz...","42,724",NaN,49
52,Uncut Gems,2019,135,7.5,With his debts mounting and angry collectors c...,"Directors:Benny Safdie, Josh Safdie","[Adam Sandler, Julia Fox, Idina Menzel, Mesfin...","142,435",NaN,90
56,Jojo Rabbit,2019,108,7.9,A young boy in Hitler's army finds out his mot...,Taika Waititi,"[Roman Griffin Davis, Thomasin McKenzie, Scarl...","185,039",$0.35M,58
58,Little Women,2019,135,7.9,Jo March (Saoirse Ronan) reflects back and for...,Greta Gerwig,"[Saoirse Ronan, Emma Watson, Florence Pugh, El...","86,951",$108.10M,91
60,Joker,2019,122,8.5,"In Gotham City, mentally troubled comedian Art...",Todd Phillips,"[Joaquin Phoenix, Robert De Niro, Zazie Beetz,...","742,309",$335.45M,59
66,Midsommar,2019,148,7.1,A couple travels to Sweden to visit a rural ho...,Ari Aster,"[Florence Pugh, Jack Reynor, Vilhelm Blomgren,...","137,300",$27.33M,72
67,Frozen II,2019,103,7.0,"Anna, Elsa, Kristoff, Olaf and Sven leave Aren...","Directors:Chris Buck, Jennifer Lee","[Kristen Bell, Idina Menzel, Josh Gad, Jonatha...","97,953",$477.37M,64
69,The Way Back,2020,108,6.8,Jack Cunningham was an HS basketball phenom wh...,Gavin O'Connor,"[Ben Affleck, Al Madrigal, Janina Gavankar, Mi...","10,200",NaN,68
70,Rocketman,I 2019,121,7.3,A musical fantasy about the fantastical human ...,Dexter Fletcher,"[Taron Egerton, Jamie Bell, Richard Madden, Br...","104,337",$96.37M,69
72,The Shawshank Redemption,1994,142,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"[Tim Robbins, Morgan Freeman, Bob Gunton, Will...","2,213,724",$28.34M,80
73,Avengers: Endgame,2019,181,8.4,After the devastating events of Avengers: Infi...,"Directors:Anthony Russo, Joe Russo","[Robert Downey Jr., Chris Evans, Mark Ruffalo,...","691,361",$858.37M,78
74,Ford v Ferrari,2019,152,8.1,American car designer Carroll Shelby and drive...,James Mangold,"[Matt Damon, Christian Bale, Jon Bernthal, Cai...","189,800",$117.62M,81
...,...,...,...,...,...,...,...,...,...,...
213,A Long Way Down,2014,96,6.4,"Four people meet on New Year's Eve, and form a...",Pascal Chaumeil,"[Pierce Brosnan, Toni Collette, Imogen Poots, ...","30,141",$0.01M,34
214,Human Traffic,1999,99,7.1,Five friends spend one lost weekend in a mix o...,Justin Kerrigan,"[John Simm, Lorraine Pilkington, Shaun Parkes,...","22,371",$0.10M,53
216,Undisputed,2002,94,6.2,"When heavyweight champion George ""Iceman"" Cham...",Walter Hill,"[Wesley Snipes, Ving Rhames, Peter Falk, Micha...","27,883",$12.40M,58
218,Teorema,1968,98,7.2,A mysterious young man seduces each member of ...,Pier Paolo Pasolini,"[Silvana Mangano, Terence Stamp, Massimo Girot...","11,215",NaN,NaN
219,Salon Kitty,1976,129,5.3,Kitty runs a brothel in Nazi Germany where the...,Tinto Brass,"[Helmut Berger, Ingrid Thulin, Teresa Ann Savo...","3,530",NaN,NaN
220,Photograph,I 2019,110,6.8,"A struggling street photographer in Mumbai, pr...",Ritesh Batra,"[Nawazuddin Siddiqui, Sanya Malhotra, Sachin K...","3,084",$0.34M,65
221,Bad Day for the Cut,2017,99,6.5,"A middle-aged Irish farmer, who still lives at...",Chris Baugh,"[Nigel O'Neill, Susan Lynch, Józef Pawlowski, ...","4,819",NaN,NaN
222,Veer-Zaara,2004,192,7.8,"Veer-Zaara is a saga of love, separation, cour...",Yash Chopra,"[Shah Rukh Khan, Preity Zinta, Rani Mukerji, K...","46,681",$2.92M,67
223,Warsaw '44,2014,130,6.6,"A story of love, friendship and the pursuit of...",Jan Komasa,"[Józef Pawlowski, Zofia Wichlacz, Anna Próchni...","4,758",NaN,NaN
224,Kim Ji-young: Born 1982,2019,118,7.4,"Kim Ji-young, an ordinary woman in her 30s, su...",Kim Do-Young,"[Yoo Gong, Yu-mi Jung, Mi-kyung Kim, Sung-Cheo...","1,330",NaN,NaN
225,American Gothic,2016,40,6.7,The members of a prominent Boston family suspe...,NaN,"[Stars:Juliet Rylance, Antony Starr, Justin Ch...","4,076",NaN,NaN
226,Atlas Shrugged: Part I,2011,97,5.6,Railroad executive Dagny Taggart and steel mog...,Paul Johansson,"[Taylor Schilling, Grant Bowler, Matthew Marsd...","12,821",$4.75M,28
228,Into the Night,1985,115,6.5,After discovering that his wife is cheating on...,John Landis,"[Jeff Goldblum, Michelle Pfeiffer, Stacey Pick...","10,446",$7.56M,41
229,The Purple Rose of Cairo,1985,82,7.7,"In New Jersey in 1935, a movie character walks...",Woody Allen,"[Mia Farrow, Jeff Daniels, Danny Aiello, Irvin...","44,919",$10.63M,75
230,Zashchitniki,2017,89,3.9,"During the Cold War, an organization called ""P...",Sarik Andreasyan,"[Anton Pampushnyy, Sanjar Madi, Sebastien Sisa...","11,043",NaN,NaN
231,The Messengers,2007,90,5.4,An ominous darkness invades a seemingly serene...,"Directors:Danny Pang, Oxide Chun Pang","[Dylan McDermott, Penelope Ann Miller, Kristen...","37,325",$35.37M,34
232,Kes,1969,111,7.9,"A young, English working-class boy spends his ...",Ken Loach,"[David Bradley, Brian Glover, Freddie Fletcher...","17,683",NaN,NaN
234,Dirty Pretty Things,2002,97,7.3,Undocumented immigrants Okwe and Senay work at...,Stephen Frears,"[Chiwetel Ejiofor, Audrey Tautou, Sophie Okone...","39,622",$8.11M,78
235,The Man from Snowy River,1982,102,7.3,"In 1880s Australia, after young Jim Craig's fa...",George Miller,"[Kirk Douglas, Tom Burlinson, Terence Donovan,...","7,568",$20.66M,63
236,Romance & Cigarettes,2005,105,6.3,A down-and-dirty musical set in the world of w...,John Turturro,"[James Gandolfini, Susan Sarandon, Kate Winsle...","11,201",$0.54M,55
237,The Train,1964,133,7.8,"In 1944, a German colonel loads a train with F...","Directors:John Frankenheimer, Arthur Penn","[Burt Lancaster, Paul Scofield, Jeanne Moreau,...","13,412",$7.41M,NaN
238,High Society,1956,111,7.0,A spoiled heiress must choose among three suit...,Charles Walters,"[Bing Crosby, Grace Kelly, Frank Sinatra, Cele...","13,115",$13.00M,NaN
239,Farming,2018,101,5.6,"Based on the writer/director's childhood, FARM...",Adewale Akinnuoye-Agbaje,"[Kate Beckinsale, Gugu Mbatha-Raw, Adewale Aki...",647,NaN,51
240,Alien Nation,1988,91,6.3,"In 1988, Earth makes the first contact with an...",Graham Baker,"[James Caan, Mandy Patinkin, Terence Stamp, Ke...","13,651",$25.22M,45
241,The Seventh Sign,1988,97,5.9,Abby Quinn is eagerly awaiting childbirth but ...,Carl Schultz,"[Demi Moore, Michael Biehn, Jürgen Prochnow, P...","12,611",$18.88M,NaN
242,Dragonwyck,1946,103,7.0,A simple Connecticut farm girl is recruited by...,Joseph L. Mankiewicz,"[Gene Tierney, Walter Huston, Vincent Price, G...","3,498",NaN,NaN
245,Affliction,1997,114,7.0,A deeply troubled small town cop investigates ...,Paul Schrader,"[Nick Nolte, Sissy Spacek, James Coburn, Brigi...","14,427",$6.30M,79
246,The House on Sorority Row,1982,91,6.0,After a seemingly innocent prank goes horribly...,Mark Rosman,"[Kate McNeil, Eileen Davidson, Janis Ward, Rob...","6,728",$1.29M,50
247,The Art of Getting By,2011,83,6.6,"George, a lonely and fatalistic teen who has m...",Gavin Wiesen,"[Freddie Highmore, Emma Roberts, Michael Angar...","54,991",$1.43M,36
248,Halloween: The Curse of Michael Myers,1995,87,4.9,Six years after Michael Myers last terrorized ...,Joe Chappelle,"[Donald Pleasence, Paul Rudd, Marianne Hagan, ...","29,467",$15.12M,10

In [12]:
movies.to_csv('movies.csv')

In [18]:
#Importing second dataset
movies_kaggle=pd.read_csv('movies_metadata.csv')

In [19]:
#Joining the two datasets
new_data=pd.merge(movies,movies_kaggle,on='title')

In [20]:
len(new_data)

7418

In [21]:
new_data.columns

Index(['title', 'year', 'duration', 'rating', 'description', 'director',
       'actors', 'votes', 'budget_x', 'metascore', 'adult',
       'belongs_to_collection', 'budget_y', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'video', 'vote_average',
       'vote_count'],
      dtype='object')